# coding=utf8
#
# http://projecteuler.net/problem=2
#
# Even Fibonacci numbers
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#

np = 0
n = 1

s = 0

while n < 4000000:
	current = n

	if (current % 2 == 0) :
		s = s + current

	n = current + np
	np = current

print(s)